#!/usr/bin/python
# vim: tabstop=4 expandtab shiftwidth=4 fileencoding=utf8
#
# Copyright (C) 2010 Peter Todd <pete@petertodd.org>

if __name__ == "__main__":
    import locale
    locale.setlocale(locale.LC_ALL, '')

    import sys

    from Congestion.main import main

    main(sys.argv)
