#!/usr/bin/python
# vim: tabstop=4 expandtab shiftwidth=4 fileencoding=utf8
# ### BOILERPLATE ###
# This file is released to the public domain.
# - Peter Todd <pete@petertodd.org>
# ### BOILERPLATE ###


"""
Example software project in Python.
"""

if __name__ == "__main__":
    import locale
    locale.setlocale(locale.LC_ALL, '')

    import sys

    from Example.main import main

    main(sys.argv)
