#!/usr/bin/python
# vim: tabstop=4 expandtab shiftwidth=4 fileencoding=utf8
# (c) 2007 Peter Todd <pete@petertodd.org>
#
# This program is made available under the GNU GPL version 2.0 or
# greater. See the accompanying file COPYING for details.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

"""
Example software project in Python.
"""

if __name__ == "__main__":
    import locale
    locale.setlocale(locale.LC_ALL, '')

    import sys

    if (len(sys.argv) > 1) and sys.argv[1] == 'test':
        from Example.tests import main
        sys.argv[0] += " test"
        del sys.argv[1]
        main(sys.argv)
    else:
        from Example.main import main
        main(sys.argv)
